# Generated by Django 5.1.7 on 2025-03-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceclass',
            options={'verbose_name_plural': 'Resource Classes'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='gittemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='resourceclass',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='user',
        ),
        migrations.AddField(
            model_name='workspace',
            name='container_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='container_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='cpu_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='disk_space_gb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='gpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='ram_gb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='git_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.gittemplate'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='resource_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.resourceclass'),
        ),
    ]
