# Generated by Django 5.1.7 on 2025-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_resourceclass_options_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gittemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='repository_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='container_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
