# Generated by Django 5.1.7 on 2025-03-29 17:11

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_remove_gittemplate_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gittemplate',
            options={'ordering': ['language', 'name']},
        ),
        migrations.AlterModelOptions(
            name='resourceclass',
            options={'ordering': ['price_per_hour'], 'verbose_name_plural': 'Resource classes'},
        ),
        migrations.AddField(
            model_name='gittemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gittemplate',
            name='default_branch',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AddField(
            model_name='gittemplate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gittemplate',
            name='setup_commands',
            field=models.JSONField(default=list, help_text='List of commands to run after cloning'),
        ),
        migrations.AddField(
            model_name='gittemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resourceclass',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='container_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('java', 'Java'), ('go', 'Go'), ('rust', 'Rust')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gittemplate',
            name='repository_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resourceclass',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='container_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='container_status',
            field=models.CharField(default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='resource_class',
            field=models.ForeignKey(default=workspaces.models.ResourceClass.get_default_class, on_delete=django.db.models.deletion.PROTECT, to='workspaces.resourceclass'),
        ),
    ]
